diabetes/urls.py
from django.urls import path
from . import views
app_name = 'diabetes'
urlpatterns = [
    path('', views.get_recommendations, name='index'),
    ]

graduationProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("diabetes.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

diabetes/models.py
from django.contrib.auth.models import User
from django.db import models


class GenderChoices(models.TextChoices):
    male = 'Male', 'Male'
    female = 'Female', 'Female'


class DiabetesTypeChoices(models.TextChoices):
    type_1 = 'Type 1', 'Type 1'
    type_2 = 'Type 2', 'Type 2'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=10, choices=GenderChoices.choices)
    diabetes_type = models.CharField(max_length=20, default=DiabetesTypeChoices.type_2,choices=DiabetesTypeChoices.choices)
    pregnancy_status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class GlucoseData(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    glucose_level = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user_profile.user.username} - {self.glucose_level} mg/dL - {self.timestamp}'

diabetes/views.py
import random
from datetime import datetime, timedelta

from django.contrib import messages
from django.db.models import Avg
from django.db.models.functions import TruncMinute, TruncSecond
from django.shortcuts import render
from numpy import *
from sklearn import *

from diabetes.models import UserProfile, GlucoseData, DiabetesTypeChoices, GenderChoices


def get_recommendations(request):
    interval = int(request.GET.get('interval', 1))
    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    if user_profile.diabetes_type == DiabetesTypeChoices.type_1:
        base_glucose_level = 100
        fluctuation_range = 30
    else:
        base_glucose_level = 120
        fluctuation_range = 20
    if user_profile.gender == GenderChoices.female:
        base_glucose_level -= 10
        fluctuation_range -= 5
        if user_profile.pregnancy_status:
            base_glucose_level += 20
            fluctuation_range += 10
    glucose_fluctuation = random.randint(-fluctuation_range, fluctuation_range)
    glucose_level = base_glucose_level + glucose_fluctuation
    glucose_level = max(70, min(glucose_level, 250))
    GlucoseData.objects.create(
        user_profile=user_profile,
        glucose_level=glucose_level,
        timestamp=datetime.now()
    )
    if interval == 1:
        every = 5
    elif interval == 5:
        every = 60
    elif interval == 10:
        every = 120
    elif interval == 15:
        every = 180
    if interval > 1:
        glucose_levels = GlucoseData.objects.filter(
            user_profile=user_profile,
            timestamp__gte=datetime.now() - timedelta(minutes=interval)
        ).annotate(minute=TruncMinute('timestamp')).values('minute', 'glucose_level').order_by('minute')
    else:
        glucose_levels = GlucoseData.objects.filter(
            user_profile=user_profile,
            timestamp__gte=datetime.now() - timedelta(minutes=interval)
        ).annotate(minute=TruncSecond('timestamp')).values('minute', 'glucose_level').order_by('minute')

    average_glucose_level = GlucoseData.objects.filter(
        user_profile=user_profile,
        timestamp__gte=datetime.now() - timedelta(minutes=interval)
    ).aggregate(Avg('glucose_level'))['glucose_level__avg']
    data = [glucose_level['glucose_level'] for glucose_level in glucose_levels]
    data = array(data)
    data = data.reshape(-1, 1)
    # clean the data
    scaler = preprocessing.StandardScaler()
    scaler.fit(data)
    data = scaler.transform(data)
    # predict the action
    model = linear_model.LinearRegression()
    model.fit(data, data)
    prediction = model.predict(data)
    prediction = scaler.inverse_transform(prediction)
    prediction = prediction[-1][0]
    if prediction > 150:
        messages.error(request,
                       f'Our Algorithm predicts that your glucose level will rise in the next {interval} {"minutes" if interval > 1 else "minute"}, please take insulin')
    elif prediction < 70:
        messages.error(request,
                       f'Our Algorithm predicts that your glucose level will drop in the next {interval} {"minutes" if interval > 1 else "minute"}, please eat something')

    return render(request, 'recommendations.html', {
        'glucose_levels': glucose_levels,
        'average_glucose_level': average_glucose_level,
        'interval': interval,
        'every': every,
        'prediction': prediction
    })

diabetes/templates/diabetes/_base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CGM</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'js/htmx.js' %}"></script>
    <script src="{% static 'js/apex.js' %}"></script>
    {% tailwind_css %}
</head>
<body class="bg-gray-50">
<nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-8 py-4">
        <div class="flex items-center justify-between">
            <a href="/" class="text-white text-2xl capitalize">continuous glucose monitoring system</a>
            <p class="text-white text-2xl capitalize">
                {% if user.is_authenticated %}
                    Welcome {{ user.username }}
                {% else %}
                    <a href="/login" class="text-white text-2xl capitalize">login</a>
                {% endif %}
            </p>
        </div>
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <script>
            const audio = new Audio('{% static 'audio/error.mp3' %}');
                audio.play();
        </script>

        <div
                class="font-regular relative block w-full rounded-lg bg-red-500 p-4 my-2 max-w-xl mx-auto text-base leading-5 text-white opacity-100"
                data-dismissible="alert"
        >
            <div class="mr-12">{{ message }}</div>
            <div
                    class="absolute top-2.5 right-3 w-max rounded-lg transition-all hover:bg-white hover:bg-opacity-20"
                    data-dismissible-target="alert"
            >
                <button
                        role="button"
                        class="w-max rounded-lg p-1"
                        data-alert-dimissible="true"
                >
                    <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-6 w-6"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                            stroke-width="2"
                    >
                        <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                d="M6 18L18 6M6 6l12 12"
                        ></path>
                    </svg>
                </button>
            </div>
        </div>
    {% endfor %}

{% endif %}


{% block content %}

{% endblock %}

</body>
</html>

diabetes/templates/diabetes/index.html
{% extends 'diabetes/_base.html' %}

{% block content %}

{% endblock %}

diabetes/templates/glucose_levels.html
<card id="glucose-chart-card" class="mt-6">
    <div class="max-w-6xl mx-auto">
            <label for="interval" class="text-left text-2xl font-bold capitalize text-gray-800">
                Interval:
            </label>
            <select id="interval" name="interval" hx-target="body" hx-get="{% url 'diabetes:index' %}"
                    class="text-center text-gray-800 border-2 border-gray-800 rounded-lg">
                <option value="1" {% if interval == 1 %} selected {% endif %} class="text-center text-gray-800">1 Minute</option>
                <option value="5" {% if interval == 5 %} selected {% endif %} class="text-center text-gray-800">5 Minutes</option>
                <option value="10" {% if interval == 10 %} selected {% endif %} class="text-center text-gray-800">10 Minutes</option>
                <option value="15" {% if interval == 15 %} selected {% endif %} class="text-center text-gray-800">15 Minutes</option>
            </select>
        </div>
    <div class="max-w-6xl mx-auto bg-white shadow-md rounded mt-4" id="glucose-chart"></div>
</card>
<script>
    function initApexCharts() {
        return window.ApexCharts && (new ApexCharts(document.getElementById('glucose-chart'), {
            series: [{
                name: "Glucose Level",
                data: [
                    {% for glucose in glucose_levels %}
                        '{{ glucose.glucose_level|floatformat:2 }}',
                    {% endfor %}
                ]
            }],
            chart: {
                background: 'transparent',
                height: 350,
                type: 'line',
                toolbar: {
                    show: false
                },
                zoom: {
                    enabled: false
                },
                animations: {
                    enabled: true,
                },
            },
            colors: ['#1d98c4'],
            stroke: {
                curve: 'straight'
            },
            grid: {
                show: false,
                row: {
                    colors: ['#f3f3f3', 'transparent'],
                    opacity: 0.5
                },
            },
            xaxis: {
                categories: [
                    {% for glucose in glucose_levels %}
                        {% if not every == 5 %}
                        '{{ glucose.minute|date:"h:i" }}',
                        {% else %}
                        '{{ glucose.minute|date:"h:m:s" }}',
                        {% endif %}
                    {% endfor %}
                ],
            },
            yaxis: {
                show: true,
                labels: {
                    show: true,
                    align: 'right',
                    style: {
                        colors: [],
                        fontSize: '12px',
                        fontWeight: 400,
                    },
                    formatter: (value) => {
                        return value + ' mg/dL';
                    },
                },

            }
        }))
    }

    document.addEventListener("DOMContentLoaded", function (evt) {
        initApexCharts().render();
    });


    document.addEventListener("htmx:afterSettle", function (evt) {
        const el = document.getElementById('glucose-chart');
        el.innerHTML = '';
        initApexCharts().render();
    });

</script>

diabetes/templates/recommendations.html
<!-- recommendations.html -->
{% extends 'diabetes/_base.html' %}
{% load static %}
{% block content %}
    <div>
        <div id="sender" hx-get="{% url 'diabetes:index' %}" hx-include="#interval" hx-swap="outerHTML"
             hx-trigger="every {{ every }}s"
             hx-target="body"></div>
        <div class=" max-w-6xl justify-center items-center mx-auto mt-4">
            <h2 class="text-center text-2xl font-bold capitalize text-gray-800">
                Glucose Level Average for The Last <span id="last"></span> <span
                    id="minute"></span>: {{ average_glucose_level|floatformat:.2 }} mg/dL
            </h2>
            <h3 class="text-center text-2xl font-bold capitalize">
                the predicted glucose level is  <span class="text-blue-500">{{ prediction|floatformat:.2 }} mg/dL </span>
            </h3>
        </div>
        {% include 'glucose_levels.html' %}
    </div>
    <script>
        document.addEventListener('htmx:afterSettle', function (event) {
            const last = document.getElementById('last');
            const minute = document.getElementById('minute');
            const interval = document.getElementById('interval');
            if (interval.value > 1) {
                minute.innerHTML = 'Minutes';
            } else {
                minute.innerHTML = 'Minute';
            }
            last.innerHTML = interval.value;
        });
        document.addEventListener('DOMContentLoaded', function (event) {
            const last = document.getElementById('last');
            const minute = document.getElementById('minute');
            const interval = document.getElementById('interval');
            if (interval.value > 1) {
                minute.innerHTML = 'Minutes';
            } else {
                minute.innerHTML = 'Minute';
            }
            last.innerHTML = interval.value;
        });
    </script>
{% endblock %}

diabetes/templates/registreation/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

diabetes/templates/registreation/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>